[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/public/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Accept-Ranges = "bytes"
    Content-Type = "video/mp4"

[[headers]]
  for = "/public/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
